// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_J90yUJ2Wbz9WLM6G90QecOeiBrnCLy4',
    appId: '1:72519425306:web:d868783bf4070872d1e0a3',
    messagingSenderId: '72519425306',
    projectId: 'flutter-login-app-7156e',
    authDomain: 'flutter-login-app-7156e.firebaseapp.com',
    storageBucket: 'flutter-login-app-7156e.appspot.com',
    measurementId: 'G-TJ88WYP707',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFVacZ1g3Rn2D2g52clm2fzSwNZyq2xP8',
    appId: '1:72519425306:android:12367accbb35b310d1e0a3',
    messagingSenderId: '72519425306',
    projectId: 'flutter-login-app-7156e',
    storageBucket: 'flutter-login-app-7156e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bq1OVKuX5ZhxwtRYd6cPAr95WXln-Gc',
    appId: '1:72519425306:ios:521b6ed47304df95d1e0a3',
    messagingSenderId: '72519425306',
    projectId: 'flutter-login-app-7156e',
    storageBucket: 'flutter-login-app-7156e.appspot.com',
    iosBundleId: 'com.example.myLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8bq1OVKuX5ZhxwtRYd6cPAr95WXln-Gc',
    appId: '1:72519425306:ios:521b6ed47304df95d1e0a3',
    messagingSenderId: '72519425306',
    projectId: 'flutter-login-app-7156e',
    storageBucket: 'flutter-login-app-7156e.appspot.com',
    iosBundleId: 'com.example.myLoginApp',
  );
}
